### ISSUE TITLE
Production healthcheck endpoint is incorrect

### ISSUE THREAD

**Issue by yusufkandemir** [serversideup/spin-template-laravel-basic#11]
In `docker-compose.prod.yml`, under `php` service, there is this code:
```
# Health check
- "traefik.http.services.my-php-app.loadbalancer.healthcheck.path=/healthcheck"
```

But, there is no note about it in the comments, nor in the documentation. The user would need to create the related endpoint themselves.

However, Laravel 11 provides a built-in healthcheck endpoint, which is enabled for newly created Laravel projects by default. Its default value is `/up`. So, as an alternative to documenting this, the easiest fix would be to update the compose file template to the following:
```
# Health check
- "traefik.http.services.my-php-app.loadbalancer.healthcheck.path=/up"
```

**Comment by jaydrogers** [comment]
The docker images are based on serversideup/php. We have it in the docs here: https://serversideup.net/open-source/docker-php/docs/guide/using-healthchecks-with-laravel

**Comment by yusufkandemir** [comment]
@jaydrogers thanks for the explanation. If I understood it correctly, that means this can be processed as a feature request. I've created a PR for this: #12

If it's incorrect, sorry for the noise.

**Comment by jaydrogers** [comment]
Makes sense. Thanks for doing the work for me 😃👍
