### ISSUE TITLE
Unknown option: --output-only

### ISSUE THREAD

**Issue by RohitLad** [serversideup/spin-template-laravel-basic#18]
For a simple `spin init laravel` command, I get the following error:

Unknown option: --output-only

Seems like the flag has been added in the latest merge.

![Screenshot 2024-12-22 161335](https://github.com/user-attachments/assets/71a060f4-62ec-4edf-8068-3b4abb07bffb)

**Comment by jaydrogers** [comment]
Make sure you run 'spin update' and are on v3.0.0+

**Comment by RohitLad** [comment]
All worked! Thanks
